### ISSUE TITLE
configure options

### ISSUE THREAD

**Issue by raveit65** [darkshram/seahorse-caja#2]
I want to include your package in official fedora, so i have a question about configure options.
You're using *--disable-gpg-check* in your spec file, what's the reason for it.
Or is this from seahorse-nautilus spec? 😄

PS: not really a issue.....

**Comment by raveit65** [comment]
Ahh, it's pretty harmless ( i guess).
```
[rave@mother seahorse-caja-1.18.1]$ ./configure --disable-gpg-check

cut

GnuPG Version:           
GPGME Version:           1.8.0
Notification Support:    yes

[rave@mother seahorse-caja-1.18.1]$ ./configure

cut

GnuPG Version:           gpg (GnuPG) 1.4.22
GPGME Version:           1.8.0
Notification Support:    yes
```

**Comment by raveit65** [comment]
Ok, without this option it checks for both versions.
BuildRequires:  gnupg
BuildRequires:  gnupg2

So, it makes sense to use it for distros where both versions are available.

**Comment by darkshram** [comment]
Sorry for the delay. Yes. That's what it does. I left pretty much the same things as upstream (static since 2014). The spec file is based on the one used for Fedora.
