### ISSUE TITLE
Support GNUPG 2.1

### ISSUE THREAD

**Issue by tsimonq2** [darkshram/seahorse-caja#4]
Hey, I'm packaging this one too. 😉 

It seems that this only supports GNUPG 2.0, but doesn't support 2.1+, which is the only version Ubuntu ships in recent releases.

Can this be fixed?

(in addition, fixing #3 would be good too)

**Comment by tsimonq2** [comment]
Er, this could be my issue...

**Comment by darkshram** [comment]
Thank you. Fixed a few minutes ago.
