### ISSUE TITLE
autotools-pkg-config-macro-not-cross-compilation-safe configure.ac (line 29)

### ISSUE THREAD

**Issue by sunweaver** [darkshram/seahorse-caja#7]
W: caja-seahorse source: autotools-pkg-config-macro-not-cross-compilation-safe configure.ac (line 29)
N: 
N:    The package appears to use AC_PATH_PROG to discover the location of
N:    pkg-config(1). This macro fails to select the correct version to support
N:    cross-compilation.
N:    
N:    A better way would be to use the PKG_PROG_PKG_CONFIG macro from pkg.m4
N:    and then using the $PKG_CONFIG shell variable.
N:    
N:    Refer to https://bugs.debian.org/884798 for details.
N:    
N:    Severity: normal, Certainty: possible
N:    
N:    Check: cruft, Type: source

**Comment by sunweaver** [comment]
Similar issue we discovered and fixed in mate-user-share:
https://github.com/mate-desktop/mate-user-share/commit/4a48e270808eb51d40a071ba43d1e37433109142

**Comment by darkshram** [comment]
Fixed and tested (ok) on master. Thank you.
